Repository WildCodeSchool-2024-09/JS-RemoteFR-Crew404-P2-Pokeflex, pull requests merged in 2024-11, with the labels that each got.

#16 S02 us09 pokeflex opens
  client/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/components/PokeflexClosed.css
  client/src/components/PokeflexClosed.tsx
  client/src/components/SeeMoreButton.css
  client/src/components/SeeMoreButton.tsx
Labels: CONFLICTS_RESOLVED

#14 S01US05
  client/index.html
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/PokeflexClosed.tsx
  client/src/components/PokelfexClosed.css
  client/src/components/SeeMoreButton.css
  client/src/components/SeeMoreButton.tsx
  client/src/main.tsx
Labels: CHANGE_REQUESTED

#45 Fix click bar
  client/src/App.css
  client/src/App.tsx
  client/src/components/Modal.css
  client/src/components/Modal.tsx
  client/src/components/PokeflexClosed.css
  client/src/components/PokeflexClosed.tsx
  client/src/components/SearchBar.css
  client/src/components/SearchBar.tsx
  client/src/components/SearchResult.tsx
  client/src/fonts/Flexo-Medium.ttf
  client/src/fonts/Montserrat-Italic-VariableFont_wght.ttf
Labels: CONFLICTS_RESOLVED

#49 add loader to trainer page
  client/public/anim_trainer_page.gif
  client/src/components/Loader.css
  client/src/components/Loader.tsx
Labels: CONFLICTS
